create database custdb;
use custdb;
select*from customer limit 20;

# What is the total revenue generated by male vs female customers
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

#Which Customers used a discount but still spend more than a average amount
select customer_id,purchase_amount 
from customer
where discount_applied='Yes' and purchase_amount >=(select AVG(purchase_amount) from customer);

#Which are the top5 product with the average review rating
SELECT item_purchased,ROUND(AVG(review_rating), 2) AS `Average Product Rating`
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

#Compare the average Purcahse Amount between standard and Express Shipping
select shipping_type,
ROUND(avg(purchase_amount),2)
from customer
where shipping_type in('Standard','Express')
group by shipping_type;

# Do subscribed Customers spend more? Compare average spend and total revenue between subscribers and non subscribers
select subscription_status,
count(customer_id)astotal_customers,
Round(avg(purchase_amount),2)as avg_spend,
Round(sum(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

# Which 5 product have the highest percentage of purchase with discounts applied?
select item_purchased,
round(sum(case when discount_applied='Yes' then 1 else 0 end) /count(*)*100,2)as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

#Segement customers into New,Returning and loyal based on their number of prevoius purchases and show the count of each segment
with customer_type as(
select customer_id,previous_purchases,
case 
	when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    End as customer_segment
from customer
)

select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment ;

# What are the top 3 most purcahsed products within each cateogry?
with item_counts as (
select category,item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc)as item_rank
from customer 
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <=3;

# Are customers who are repeat buyers(more thab previous purchases) also likely to subscriber?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status;
 
# What is the revenue contribution of each age group ?
select age_group,
sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc;


